GET http://localhost:3003/api/blogs


####
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "First Blog",
  "author": "Utkarsh Tester",
  "url": "fajjall.com",
  "likes": 0
}
