GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons/680c140b3bf0f670e54d5026

###
GET http://localhost:3001/api/persons/8

###
DELETE http://localhost:3001/api/persons/68098bc734d00df13a7d83e0

###
POST  http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Utkarsh M",
  "number": "9892221144"
}

###
POST  http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "number": "Utkarsh Majithia"
}

###
PUT http://localhost:3001/api/persons/680c140b3bf0f670e54d5026 HTTP/1.1
content-type: application/json

{
  "name": "John Pork",
  "number": "38130"
}